import {
  Dialog,
  DialogTrigger,
} from '../components/neobrutalism/dailog';
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ReviewCard from "../components/ReviewCard";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import LookingforSWE_Header from "../components/LookingforSWE.header";
import CTA from "../components/CTA";
import Footer from "../components/Footer";
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from '../components/neobrutalism/pagination'
import { Button } from "../components/neobrutalism/button";
import { PenLine } from "lucide-react";
import Pencho from "../models/pencho";
import { getPencho } from "../db";
import { Input } from '../components/neobrutalism/input';
import { AddPenchoDialog } from '../components/addPencho.dialog';
import { HomePageClient } from './_index';
const penchoList: Pencho[] = [
  {
      id: "1",
      title: "First Pencho",
      description: "Description of the first Pencho",
      upvotes: 10
  },
  {
      id: "2",
      title: "Second Pencho",
      description: "Description of the second Pencho",
      upvotes: 15
  },
  {
      id: "3",
      title: "Third Pencho",
      description: "Description of the third Pencho",
      upvotes: 5
  }
];


const Home: NextPage = () => {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button className="!h-14 !text-white fixed bg-[#2F2F2F] bottom-4 right-4 z-20">
          <PenLine color="white" className="mr-0 md:mr-4" size={32} />
          <span className="hidden md:block">Add Your Experiences</span>

        </Button>
      </DialogTrigger>

      <Head>
        <title>Pehencho.WTf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&family=Zilla+Slab:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>


      <LookingforSWE_Header />
      <motion.div
        initial={{ opacity: 0, scale: 0.5 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.3 }} >
        <CTA />
      </motion.div>
      <motion.div
        initial={{ translateY: 500, opacity: 0 }}
        animate={{ translateY: 0, opacity: 1 }}
        transition={{ duration: 0.3 }}
      >
        <HomePageClient posts={penchoList}/>
      </motion.div>

      <Pagination className="mt-24">
        <PaginationContent>
          <PaginationItem>
            <PaginationPrevious href="#" />
          </PaginationItem>
          <PaginationItem>
            <PaginationLink href="#">1</PaginationLink>
          </PaginationItem>
          <PaginationItem>
            <PaginationLink href="#" isActive>
              2
            </PaginationLink>
          </PaginationItem>
          <div className="items-center md:flex hidden">
            <PaginationItem>
              <PaginationLink href="#">3</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationEllipsis />
            </PaginationItem>
          </div>
          <PaginationItem>
            <PaginationNext href="#" />
          </PaginationItem>
        </PaginationContent>
      </Pagination>;
      <motion.div
        initial={{ opacity: 0, y: 500 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }} >
        <Footer />
      </motion.div>
      <AddPenchoDialog />
    </Dialog>
  );
};

export default Home;
