"use client"
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import ReviewCard from "../components/ReviewCard";
import { motion } from "framer-motion";
import { useEffect, useState } from "react";
import LookingforSWE_Header from "../components/LookingforSWE.header";
import CTA from "../components/CTA";
import Footer from "../components/Footer";
import Pencho from "../models/pencho";
import { getPencho, getPenchoRT } from "../utils/supabase.wrapper";
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationItem,
  PaginationLink,
  PaginationNext,
  PaginationPrevious,
} from '../components/neobrutalism/pagination'
import { Button } from "../components/neobrutalism/button";
import { PenLine } from "lucide-react";
const reviewCards = [
  {
    title: "Great Product",
    description: "I absolutely love this product! It exceeded my expectations.",
    id: 1,
    rank: 5,
  },
  {
    title: "Good Quality",
    description:
      "The quality of this product is excellent. I highly recommend it.",
    id: 2,
    rank: 4,
  },
  {
    title: "Average Experience",
    description:
      "My experience with this product was average. It did the job, but nothing exceptional.",
    id: 3,
    rank: 3,
  },
  {
    title: "Not Satisfied",
    description:
      "Unfortunately, I wasn't satisfied with this product. It didn't meet my expectations.",
    id: 4,
    rank: 2,
  },
  {
    title: "Poor Quality",
    description:
      "I'm very disappointed with the quality of this product. It's not worth the price.",
    id: 5,
    rank: 1,
  },
];
const Home: NextPage = () => {
  const [posts, setPost] = useState<Pencho[] | undefined>();
  useEffect(() => {
    getDocuments();
  }, []);
  const getDocuments = async () => {
    getPenchoRT(1, 2);
    // const querySnapshot = await getDocs(collection(db, "penchos"));

    // const penchos = querySnapshot.docs.map(doc => {
    //   const data = doc.data();
    //   return {
    //     title: data.title || "",
    //     content: data.content || "",
    //     upvotes: data.upvotes || 0,
    //     id: doc.id
    //   } as Pencho;
    // });

    // setPost(penchos);
  }
  return (
    <div>
      <Button  className="!h-14 !text-white fixed bg-[#2F2F2F] bottom-4 right-4 z-20">
        <PenLine color="white" className="mr-0 md:mr-4"  size={32} />
        <span className="hidden md:block">Add Your Experiences</span>
        
      </Button>
      <Head>
        <title>Pehencho.WTf</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&family=Zilla+Slab:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
      </Head>


      <LookingforSWE_Header />
      <motion.div
        initial={{ opacity: 0, scale: 0.5 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.3 }} >
        <CTA />
      </motion.div>
      {(reviewCards != undefined) ?
        <motion.div
          initial={{ translateY: 500, opacity: 0 }}
          animate={{ translateY: 0, opacity: 1 }}
          transition={{ duration: 0.3 }}
        >

          <div className="max-w-xl mx-auto flex flex-col mt-8  px-4 space-y-4">
            {
              reviewCards.map((post, index) => (
                <ReviewCard
                  id={`${post.id}`}
                  title={post.title}
                  description={post.description}
                  rank={index + 1}
                  upvotes={1}
                />
              ))}
          </div>
        </motion.div> : null}

      <Pagination className="mt-24">
        <PaginationContent>
          <PaginationItem>
            <PaginationPrevious href="#" />
          </PaginationItem>
          <PaginationItem>
            <PaginationLink href="#">1</PaginationLink>
          </PaginationItem>
          <PaginationItem>
            <PaginationLink href="#" isActive>
              2
            </PaginationLink>
          </PaginationItem>
          <div className="items-center md:flex hidden">
            <PaginationItem>
              <PaginationLink href="#">3</PaginationLink>
            </PaginationItem>
            <PaginationItem>
              <PaginationEllipsis />
            </PaginationItem>
          </div>
          <PaginationItem>
            <PaginationNext href="#" />
          </PaginationItem>
        </PaginationContent>
      </Pagination>;
      <motion.div
        initial={{ opacity: 0, y: 500 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }} >
        <Footer />
      </motion.div>

    </div>
  );
};

export default Home;
